# Generated by Django 5.0.6 on 2024-05-16 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blogpost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="cover_img/"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
