# Generated by Django 5.0.6 on 2024-05-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogpost_cover_image_blogpost_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="date",
            new_name="post_date",
        ),
    ]
