# Generated by Django 5.0.6 on 2024-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="created_at",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="updated_at",
            new_name="last_modified",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="url_identifier",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(
                help_text="Za kontakt u slučaju zahteva ili upita (ne prikazuje se javno)",
                max_length=254,
            ),
        ),
    ]
