# Generated by Django 5.0.6 on 2024-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_rename_created_at_blogpost_created_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Za kontakt u slučaju zahteva ili upita (ne prikazuje se javno)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
