# Generated by Django 5.0.6 on 2024-05-30 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_comment_parent_alter_comment_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="likes",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(
                help_text="Za kontakt u slučaju zahteva ili upita (ne prikazuje se javno)",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
