# Generated by Django 5.0.6 on 2024-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_comment_content_alter_comment_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="snippet",
            field=models.TextField(default=""),
        ),
    ]
