# Generated by Django 5.0.6 on 2024-06-11 17:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_profile_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, max_length=500, verbose_name="Text"
            ),
        ),
    ]
