# Generated by Django 5.0.6 on 2024-06-22 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="likes",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
