# Generated by Django 5.0.6 on 2024-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_blogpost_likes_alter_blogpost_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/cover_img/"),
        ),
    ]
