# Generated by Django 5.0.6 on 2024-06-22 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
                ("isbn", models.CharField(blank=True, max_length=13, null=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SCI_ART", "Naučni rad"),
                            ("SCI_BOOK", "Naučna knjiga"),
                            ("SCI_POP", "Popularna nauka"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("RS", "Srpski"),
                            ("BG", "Bugarski"),
                            ("EN", "Engleski"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="literature_pdfs/"
                    ),
                ),
                ("external_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("place", models.CharField(max_length=50)),
                ("website", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LiteratureContributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AUTHOR", "Autor"),
                            ("CO_AUTHOR", "Koautor"),
                            ("EDITOR", "Editor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lt_contributors",
                        to="booklibrary.contributor",
                    ),
                ),
                (
                    "literature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lt_contributors",
                        to="booklibrary.literature",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="literature",
            name="contributors",
            field=models.ManyToManyField(
                through="booklibrary.LiteratureContributor",
                to="booklibrary.contributor",
            ),
        ),
        migrations.AddField(
            model_name="literature",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="literatures",
                to="booklibrary.publisher",
            ),
        ),
    ]
