# Generated by Django 5.0.6 on 2024-07-01 10:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="literature",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="literature",
            name="publisher",
        ),
        migrations.AddField(
            model_name="literature",
            name="publication_year",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
        migrations.AddField(
            model_name="literature",
            name="publishers",
            field=models.ManyToManyField(blank=True, to="booklibrary.publisher"),
        ),
        migrations.AddField(
            model_name="literature",
            name="udc_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="literature",
            name="category",
            field=models.CharField(
                choices=[
                    ("SCI_ART", "Naučni rad"),
                    ("SCI_BOOK", "Naučna knjiga"),
                    ("THES_DIS", "Teza/Disertacija"),
                    ("SCI_POP", "Popularna nauka"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issn", models.CharField(blank=True, max_length=10, null=True)),
                ("editor", models.CharField(blank=True, max_length=255, null=True)),
                ("publishers", models.ManyToManyField(to="booklibrary.publisher")),
            ],
        ),
        migrations.AddField(
            model_name="literature",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booklibrary.journal",
            ),
        ),
        migrations.AddField(
            model_name="literature",
            name="subjects",
            field=models.ManyToManyField(to="booklibrary.researchsubject"),
        ),
    ]
