# Generated by Django 5.0.6 on 2024-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booklibrary",
            "0002_researchsubject_remove_literature_publication_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name="literature",
            name="contributors",
        ),
        migrations.RemoveField(
            model_name="literaturecontributor",
            name="contributor",
        ),
        migrations.RemoveField(
            model_name="literaturecontributor",
            name="literature",
        ),
        migrations.AddField(
            model_name="literature",
            name="authors",
            field=models.ManyToManyField(to="booklibrary.author"),
        ),
        migrations.DeleteModel(
            name="Contributor",
        ),
        migrations.DeleteModel(
            name="LiteratureContributor",
        ),
    ]
