# Generated by Django 5.0.6 on 2024-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0003_author_remove_literature_contributors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
