# Generated by Django 5.0.6 on 2024-07-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0004_alter_author_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literature",
            name="udc_number",
        ),
    ]
