# Generated by Django 5.0.6 on 2024-07-01 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0005_remove_literature_udc_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symposium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("isbn", models.CharField(blank=True, max_length=13, null=True)),
                ("issn", models.CharField(blank=True, max_length=10, null=True)),
                ("editor", models.CharField(blank=True, max_length=255, null=True)),
                ("publishers", models.ManyToManyField(to="booklibrary.publisher")),
            ],
        ),
        migrations.AddField(
            model_name="literature",
            name="symposium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booklibrary.symposium",
            ),
        ),
    ]
