# Generated by Django 5.0.6 on 2024-07-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0006_symposium_literature_symposium"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Symposium",
            new_name="ConferenceSymposium",
        ),
        migrations.RenameField(
            model_name="literature",
            old_name="symposium",
            new_name="conf_symp",
        ),
    ]
