# Generated by Django 5.0.6 on 2024-07-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booklibrary",
            "0008_rename_conferencesymposium_scientificconference_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="literature",
            name="category",
            field=models.CharField(
                choices=[
                    ("SCI_ART", "Naučni rad"),
                    ("SCI_BOOK", "Naučna knjiga"),
                    ("THES_DIS", "Teza/Disertacija"),
                    ("SCI_POP", "Popularna nauka"),
                    ("PROJECT", "Projekat"),
                ],
                max_length=10,
            ),
        ),
    ]
