# Generated by Django 5.0.6 on 2024-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0009_journal_website_alter_literature_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="literature",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="literature/cover_img"
            ),
        ),
        migrations.AlterField(
            model_name="literature",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="literature/pdf/"),
        ),
    ]
