# Generated by Django 5.0.6 on 2024-07-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0010_literature_cover_image_alter_literature_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="literature",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="literature/cover_img/"
            ),
        ),
    ]
